
import type {Mesh, MeshStandardMaterial} from 'three'

import { useGLTF } from '@react-three/drei'
import type { JSX } from 'react';



export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/keyboard.glb');

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['0_KEY'] as Mesh).geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['1_KEY'].geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['2_KEY'].geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['3_KEY'].geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['4_KEY'].geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['5_KEY'].geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['6_KEY'].geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['7_KEY'].geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['8_KEY'].geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['9_KEY'].geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ALT_KEY.geometry}
        material={materials.grayKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ALTGR_KEY.geometry}
        material={materials.grayKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BACKSLASH_KEY.geometry}
        material={materials.grayKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA1_PART1.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA1_PART2.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA2_PART2.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA2_PART3.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA3_PART1.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA3_PART2.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA3_PART3.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA4_PART1.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA4_PART2.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA4_PART3.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA5_PART1.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA5_PART2.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA5_PART3.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA5_PART4.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA5_PART5.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA5_PART6.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA5_PART7.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA5_PART8.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA5_PART9.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_FILA_2_PART1.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_TECLADO.geometry}
        material={materials.plate}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.C_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.COMILLAS_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CTRL2_KEY.geometry}
        material={materials.grayKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CTRL_KEY.geometry}
        material={materials.grayKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.D_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DEL_KEY.geometry}
        material={materials.grayKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DOS_PUNTOS_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.E_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ENTER_KEY.geometry}
        material={materials.grayKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.F_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA1_PART1.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA1_PART2.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA2_PART1.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA2_PART2.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA2_PARTE3.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA3_PART1.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA3_PART2.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA3_PART3.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA4_PART1.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA4_PART2.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA4_PART3.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA5_PART1.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA5_PART2.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA5_PART3.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA5_PART4.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA5_PART5.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA5_PART6.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA5_PART7.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA5_PART8.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FILA5_PART9.geometry}
        material={materials.switchColor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.G_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GUION_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GUION_ONDA_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.H_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HOME2_KEY.geometry}
        material={materials.grayKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HOME_KEY.geometry}
        material={materials.grayKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.I_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.IAGUAL_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.J_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.K_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.L_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LLAVE_ABIERTA_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LLAVE_CERRADA_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.M_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MAY_KEY.geometry}
        material={materials.grayKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MAYOR_QUE_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MENOR_QUE_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MENU_KEY.geometry}
        material={materials.grayKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.N_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.O_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.P_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Q_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.R_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.S_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHIFT_1_KEY.geometry}
        material={materials.grayKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHIFT_2_KEY.geometry}
        material={materials.grayKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SIGNO_PREGUNTA_KEY.geometry}
        material={materials.plate}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPACE_KEY.geometry}
        material={materials.grayKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.T_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TAB_KEY.geometry}
        material={materials.grayKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.U_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.V_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.W_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.X_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Y_KEY.geometry}
        material={materials.whiteKeys}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Z_KEY.geometry}
        material={materials.whiteKeys}
      />
    </group>
  )
}

useGLTF.preload('/keyboard.glb')